spring:
  application:
    name: order-services
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomm_order_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8083

