server:
  port: 8888
spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_REPOURL}
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_ACCESS_TOKEN}

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true




